version: "3.8"

services:
  webserver:
    restart: unless-stopped
    depends_on:
      - backend
      - auth-server
    image: did-auth-proxy-webserver
    build:
      context: nginx
    ports:
      - "127.0.0.1:8080:80"
    networks:
      backend:

  backend:
    restart: unless-stopped
    image: did-auth-proxy-backend
    build:
      context: backend-server
    networks:
      backend:

  auth-server:
    depends_on:
      - redis
    restart: unless-stopped
    image: did-auth-proxy-auth-server
    build:
      context: authorization-server
    environment:
      - LOG_LEVELS=log,warn,error,debug,verbose
      - PORT=80
      - RPC_URL=https://volta-rpc.energyweb.org/
      - CACHE_SERVER_URL=https://identitycache-dev.energyweb.org/v1
      - CACHE_SERVER_LOGIN_PRVKEY=eab5e5ccb983fad7bf7f5cb6b475a7aea95eff0c6523291b0c0ae38b5855459c
      - DID_REGISTRY_ADDRESS=0xc15d5a57a8eb0e1dcbe5d88b8f9a82017e5cc4af
      - ENS_REGISTRY_ADDRESS=0xd7CeF70Ba7efc2035256d828d5287e2D285CD1ac
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=redis
      - JWT_SECRET=asecretstring
      - ACCEPTED_ROLES=
      - JWT_ACCESS_TTL=3600
      - JWT_REFRESH_TTL=86400
      - AUTH_COOKIE_NAME=Auth
      - AUTH_COOKIE_ENABLED=false
    networks:
      backend:

  redis:
    image: bitnami/redis:latest
    restart: unless-stopped
    ports:
      - '127.0.0.1:6379:6379'
    environment:
      - REDIS_PASSWORD=redis
    networks:
      backend:
    volumes:
      - redis-data:/bitnami/redis/data

volumes:
  redis-data:

networks:
  backend:
